### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by VailStudio** [duonanotte/Blum#1]
Traceback (most recent call last):
  File "C:\Users\mwahy\OneDrive\Desktop\AIRDROP\blum\Blum\main.py", line 4, in <module>
    from bot.utils.banner import banner
  File "C:\Users\mwahy\OneDrive\Desktop\AIRDROP\blum\Blum\bot\utils\__init__.py", line 1, in <module>
    from . import launcher
  File "C:\Users\mwahy\OneDrive\Desktop\AIRDROP\blum\Blum\bot\utils\launcher.py", line 8, in <module>
    from bot.config import settings
  File "C:\Users\mwahy\OneDrive\Desktop\AIRDROP\blum\Blum\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\mwahy\OneDrive\Desktop\AIRDROP\blum\Blum\bot\config\config.py", line 23, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\mwahy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\main.py", line 152, in __init__
    super().__init__(
  File "C:\Users\mwahy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
POINTS
  Input should be a valid list [type=list_type, input_value=280, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/list_type

**Comment by duonanotte** [comment]
In config.py

POINTS: list[int] = [190, 230]
